### ISSUE TITLE
`nightly` no longer required

### ISSUE THREAD

**Issue by djdembeck** [book-tools/audnexus-kometa-series#2]
Hey there!

I just got this all setup last night - great work putting the guide together.

`album_mood` is now available in `:latest` docker tags.

**Comment by csandman** [comment]
Awesome, glad it worked for you! And thanks, I hadn't really tried latest in a while and didn't really want to mess up my existing library in case it wasn't working right. I'll update the readme!

**Comment by csandman** [comment]
Well, I completely forgot about this, but I finally updated the docs to no longer talk about the `nightly` part haha. I also updated the guide to reference the tool's new name ["Kometa"](https://kometa.wiki/en/latest/) instead of Plex-Meta-Manager.
